plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.korkutsoftware.hilalim'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.korkutsoftware.hilalim"
        minSdk 24
        targetSdk 37
        versionCode 2
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    

    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.play.services.location

    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}